name: build jar package

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 16
      - name: build spigot
        run: |
          mkdir spigot
          cd spigot
          wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
          java -jar BuildTools.jar --rev 1.17.1
          cd Bukkit
          mvn install
          cd ../CraftBukkit
          mvn install
          cd ../../
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: build/libs